#-------------------------------
# General Site Settings
title: SuBin Seo 
logo: logo.svg # You can add own logo.
description: Subin's lifelog blog ! 


#-------------------------------
# Author Settings
author:
  name: Subin Seo 
  image: 01.jpg
  say-hello: Welcome! This is <strong>SuBin Seo.</strong>
  bio: I am a versatile researcher with <a href="#">interdisciplinary</a> academic bases. I have <a href="#">triple</a> bachelor's degrees , Information and Library science ,Psychology and Statistics. Find out more about me on this blog!


