#-------------------------------
# General Site Settings
title: SuBin Seo 
logo: logo.svg # You can add own logo.
description: Subin's lifelog blog ! 


#-------------------------------
# Author Settings
author:
  name: Subin Seo 
  image: 01.jpg
  say-hello: Hello, I'm <strong>Subin Seo.</strong>
  bio: I am interested in exploring <a href="#">Information Behavior</a> and <a href="#">User Experience </a>from a <b href="#">multidisciplinary perspective</b> based on my triple degree (LIS, Psychology, Statistics), utilizing <b href="#">Data-Driven Research Methods.</b>  Find out more about me on this blog ! 