#-------------------------------
# General Site Settings
title: SuBin Seo 
logo: logo.svg # You can add own logo.
description: Subin's lifelog blog ! 


#-------------------------------
# Author Settings
author:
  name: Subin Seo 
  image: 01.jpg
  say-hello: Hello, I'm <strong>Subin Seo.</strong>
  bio: I am interested in mixed-methods research to understand <b href="#">Information behavior</b> and <b href="#">Human-computer interaction</b> with a <b href="#">multidisciplinary</b> approach. Find out more about my story on this blog ! 